#DATABASE
MYSQL_USERNAME: root
MYSQL_PASSWORD:
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: batch1
MYSQL_URL: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
MYSQL_DRIVER: com.mysql.cj.jdbc.Driver

#SERVER
SERVER_PORT: 8080
ACTIVE_PROFILE: dev